# Introduction

The Gulf of Maine Research Institute is a collaborative workplace composed of a number of research labs and their PI's. We collaborate frequently with external partners and strive to produce high-quality, reproducible, and transparent research.



## How We Meet

Each lab at GMRI is organized independently to  suite the needs and availability of that group. Labs generally meet once a week for a check-in and for planning that week's schedule. The larger research team meets routinely every other week to discuss higher level updates and planning. These meetings are flexible and are open to updates from individuals that have something they wish to share. 

## Who to Contact
HR support: email hr@gmri.org (see HR section under Onboarding for more info)
IT support: email help@gmri.org (see IT section under Onboarding for more info)




## Where to Find Things



## GMRI  Intranet

GMRI’s Intranet is a central location for GMRI internal information. Our intranet is a website managed through sharepoint in which the purpose is to work towards the strategic plan goal of “investing in technology that empowers staff with skills and tools for innovation, collaboration, and efficiency”. 

**Ways to access the Intranet include:**   

* This link: https://gmri365.sharepoint.com/sites/GMRIHome   
* From office365, clicking on the app launcher in the top left hand corner, clicking “all apps”, then scrolling down to the “GMRI Intranet” tab.   

**GMRI Intranet has information on:**   

* Previously recorded staff meeting presentations.    
* GMRI interactive phone list    
* Staff events    
* Benefit documents    
* GMRI policies    
* Resources for hiring managers    
* IT documentation    
* Application cheat sheets and tips    
* Forms you may need to fill out    
* Web links to Paylocity, Zoom (specific room zoom links), benefit portal links    
* Has search engine for fast and effective search    

### Box

### Drive

